### ISSUE TITLE
Cannot enhance items in 7.2.0 version

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#100]
Cannot enhance items in 7.2.0 version (#389)

可以如常打开强化界面 :
https://imgur.com/a/OslvU8U

但放物品上去之后就变这样子了 :
https://imgur.com/a/TjFfxAx

伺服器那边跑出这堆东西 :
https://imgur.com/a/js9PkTR

另外 工具强化模式用不了
(点击十字镐后 什么也放不上去0.0)
但没有跑出任何东西

**Comment by 25** [comment]
Plugin cannot find `requireConcentratedStones`

Could you check config?
