### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#101]
Error in server console when launch 

https://imgur.com/a/X5LpyfY

**Comment by 25** [comment]
https://codebeautify.org/yaml-validator/cb4d11b2

**Comment by lgou2w** [comment]
@AndiSlash0723 Fixed in [390](http://www.soulbound.me/job/EnchantmentsEnhance_stable/390/).

**Comment by AndiSlash0723** [comment]
@lgou2w thanks ^^ i will test it right now

**Comment by AndiSlash0723** [comment]
Didn't see any bugs / glitch by far 0.0

If it has any glitch / bug, i will report it in here ^^

Thank you
