### ISSUE TITLE
The commit of SPIGOT-2540 cause the build to failed

### ISSUE THREAD

**Issue by lgou2w** [25/EnchantmentsEnhance#104]
See : https://hub.spigotmc.org/jira/browse/SPIGOT-2540
See : https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/3f0591ead707879a05dac22aa958af75e7e1b97e

**Comment by lgou2w** [comment]
See #105 . But I have not tested

**Comment by 25** [comment]
Thank you! 
The patch has been merged.
