### ISSUE TITLE
Problem enhancing/changing item grade

### ISSUE THREAD

**Issue by Auroaa** [25/EnchantmentsEnhance#11]
### What behaviour is observed:
Enhancement won't go up after +6, black stone count won't go down indicating I've used one, yet the server chat becomes spammed with "you have used a black stone. Console features something different. Enhance reform doesn't even work, doesn't recognize the command.

### What behaviour is expected:
To enhance past +6 (have done it before in earlier versions) and to reform items to a higher grade.

### Steps/models to reproduce:
Enhancing up to +6 and trying beyond that - as well as /enhance reform - brings up "invalid command"

### Plugin list:
[http://prntscr.com/k2n4tm](url)

### Environment description
Spigot - 1.12.2 (not entirely sure if this is what you meant)

### Enchantments Enhance build number:
V4.4

### Error Log:
04.07 16:57:47 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 0
04.07 16:57:47 [Server] WARN at org.pixeltime.enchantmentsenhance.command.player.ItemCommand.onCommand(ItemCommand.kt:16)
04.07 16:57:47 [Server] WARN at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:136)
04.07 16:57:47 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
04.07 16:57:47 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
04.07 16:57:47 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
04.07 16:57:47 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
04.07 16:57:47 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
04.07 16:57:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
04.07 16:57:47 [Server] WARN at java.lang.Thread.run(Thread.java:745)

------------------------------------
04.07 17:01:01 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
04.07 17:01:01 [Server] INFO Caused by: java.lang.NullPointerException
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.manager.ItemManager.addlore(ItemManager.java:131) ~[EnchantmentsEnhance-4.4.jar:4.4]
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItem(ItemManager.java:120) ~[EnchantmentsEnhance-4.4.jar:4.4]
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.event.blackspirit.Enhance.enhanceSuccess(Enhance.java:89) ~[EnchantmentsEnhance-4.4.jar:4.4]
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.event.blackspirit.Enhance.diceToEnhancement(Enhance.java:179) ~[EnchantmentsEnhance-4.4.jar:4.4]
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.lambda$update$0(MainMenu.java:55) ~[EnchantmentsEnhance-4.4.jar:4.4]
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$$Lambda$111/843797242.click(Unknown Source) ~[?:?]
04.07 17:01:01 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.GUIListener.onClick(GUIListener.java:56) ~[EnchantmentsEnhance-4.4.jar:4.4]
04.07 17:01:01 [Server] INFO at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source) ~[?:?]
04.07 17:01:01 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
04.07 17:01:01 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
04.07 17:01:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
04.07 17:01:04 [Multicraft] Skipped 125 lines due to rate limit (30/s)
04.07 17:01:04 [Server] ERROR Could not pass event InventoryClickEvent to EnchantmentsEnhance v4.4

**Comment by 25** [comment]
I can confirm that all the issues are resolved. Thank you for reporting.
