### ISSUE TITLE
items get lost due to the main gui

### ISSUE THREAD

**Issue by botboy0** [25/EnchantmentsEnhance#117]
### What behaviour is observed:
there is a game breaking bug. when you shiftclick or drag items into the main enhancement gui ,  it actually goes into one of the empy slots and you cant take the item out , the gui closes and the item is lost

### Steps to reproduce:
by putting my item into one of the empty slots in the enhancement gui
![2019-04-26_16 08 54](https://user-images.githubusercontent.com/10763071/56813641-b033f680-683d-11e9-9748-ddb2e457be65.png)

### Plugin list:
attached as an image

### Environment description
Spigot 1.12 plugin version: 7.2.0

### Enchantments Enhance build number:
7.2.0

### Error Log:
no error

**Comment by botboy0** [comment]
![2019-04-26_16 11 58](https://user-images.githubusercontent.com/10763071/56813802-0d2fac80-683e-11e9-920d-cfdf0b9ba7c6.png)

This in the image of the sword going into the slot before it gets lost by the closed gui

**Comment by 25** [comment]
I did manual tests but I can't seem to reproduce this. Are you using the latest version of EE?

**Comment by botboy0** [comment]
yes it is the newest version of the plugin 7.2.0

**Comment by botboy0** [comment]
and I also tried only having vault and this plugin on the server , it still has the same bug

**Comment by 25** [comment]
Have you tried to update your spigot jar?

**Comment by botboy0** [comment]
I have the newest version of spigot 1.12.2

**Comment by botboy0** [comment]
My issue still couldnt be resolved after trying multiple versions including the nwest versions of spigot and this plugin.  are you sure you understand where the bug is? I can shiftclick and even drag any item with leftclick into one of the empy slots and it stays there and when trying to take the item out it immediatly closes the gui and the item is lost. it is impossible that only i have the bug /:  I really need this plugin to work

**Comment by botboy0** [comment]
feel free to message me on Discord so we can both test it out on my testserver
name: mr_mysterium#7630

**Comment by 25** [comment]
I tried the build you gave me. I could not reproduce the error you have described.
