### ISSUE TITLE
Error when clicking empty slots with menu opened

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#122]
After opening up the menu, error will occurred when clicking on empty slots (Menu and inventory).

Error message in console : 
https://imgur.com/a/32maZtC

There are 2 errors, one of them is : 
https://pastebin.com/M7jyweUP

the another one is : 
https://pastebin.com/x3wZpeZh

Server version : 1.14 Bukkit
Also, the plugin works well on 1.14, can enhance items normally.
As far as I know, error will only occurred when clicking on empty slots with menu opened

Thank you !

(有朋友说 发生错误是因为pointer无效
有点好奇他指的pointer是指什么?)

**Comment by lgou2w** [comment]
See line 46 :
No detection `getCurrentItem` null pointer.
https://github.com/25/EnchantmentsEnhance/blob/a6cc320dccf330465d3bb6b6d38b99253ea21e03/EnchantmentsEnhance-Plugin/src/main/java/org/pixeltime/enchantmentsenhance/gui/menu/handlers/MenuHandler.java#L45-L48

**Comment by 25** [comment]
@lgou2w Thank you! Fixed the issue.

@AndiSlash0723 Thanks for reporting, 1.14 is now supported
