### ISSUE TITLE
Error on 1.14 Paper Spigot

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#128]
I got this error when running the plugin on 1.14 PaperSpigot.

https://imgur.com/a/6rtDB9p
( https://pastebin.com/izvKC6ci )

Not sure what happened, the version of PaperSpigot I was running is "Paper-1.14-b8"

Thank you

**Comment by lgou2w** [comment]
Does the problem still exist? Why is this issue closed? @AndiSlash0723

**Comment by AndiSlash0723** [comment]
@lgou2w Not solved yet... But I feel.. I was using a dev build?...
I test that Paper Spigot version and my friends said bukkit was better that it..

I think I should wait for the full version of 1.14 Paper Spigot, so I closed the issue..

**Comment by AndiSlash0723** [comment]
@lgou2w I downloaded it from here : https://yivesmirror.com/downloads/paper
(Seems its a dev build, not ready yet)

Many people recommend to wait for 1.14.1 
I think I will test if the plugin works or not on 1.14.1 when 1.14.1 Bukkit is out
(Maybe it's gonna be a long time)

**Comment by lgou2w** [comment]
I did not find the reason for the update in the `spigotmc` community. But found this update on [`paper`](https://github.com/PaperMC/Paper), see below:

https://github.com/PaperMC/Paper/blob/fb25dc17c62acce335346d5e96899257ae7230c7/Spigot-Server-Patches/0319-Fix-client-rendering-skulls-from-same-user.patch#L22-L23

This is the reason for `LDK` itself.

**Comment by lgou2w** [comment]
Because `LDK` is based on `spigot`, there may be unknown risks for `paper`. I will fix this as soon as possible, thank you for your feedback. :3

**Comment by AndiSlash0723** [comment]
Yea its PaperSpigot (Or maybe people call them "Paper" only? I think I may made a mistake)

Back to the reason of closing the issue is because I think I was using a dev build of it :/

**Comment by AndiSlash0723** [comment]
Nah XD

We moved back to Bukkit :3

**Comment by lgou2w** [comment]
XD, I don't know much about `paper`, I know it's based on the optimized version of `spigot`, so there are some problems.

**Comment by AndiSlash0723** [comment]
But still... I think.. maybe should wait for the full version of Paper before fixing it..

**Comment by lgou2w** [comment]
yes, you can use spigot first. :3

**Comment by AndiSlash0723** [comment]
I saw this a few days ago ( https://forum.gamer.com.tw/Co.php?bsn=18673&sn=813637 )

And some people said Paper could reduce lags on the server...

But what I got today is a feedback from my friend about Paper has more lag than Bukkit
So we switched back to Bukkit..

Or maybe its because the .bat file setting / without plugins like ClearLagg, EscapeLag

**Comment by AndiSlash0723** [comment]
BTW, but does Spigot support Bukkit plugins?

Like I just mentioned, I'm currently running 1.14 Bukkit..
So all the plugins are Bukkit plugins..

Is it possible to move all of them into Spigot =.=?!

**Comment by lgou2w** [comment]
Yes, because spigot is based on an optimized version of bukkit, and bukkit is now also maintained by the spigotmc community. But do not rule out some problems caused by plugins that stop updating.

**Comment by AndiSlash0723** [comment]
Thank you for that, I will try using Spigot..

Hmm, but can Spigot reduce lags? 
Because 1.14 Bukkit is quite lag, TPS is very low even if there are 3 people online in the same area. ://

**Comment by lgou2w** [comment]
Spigot is optimized, if the server performance is good, the basic one can accommodate 100 people online

**Comment by AndiSlash0723** [comment]
But how can I let the server to have a good performance..
Because I'm running the server with 8GB on my own computer, but still laggy..

The lag is really annoying to us..

**Comment by lgou2w** [comment]
Is it a survival server ? is the world saves very large?

**Comment by AndiSlash0723** [comment]
Yea a survival server, the world is quite new. Not very large

**Comment by lgou2w** [comment]
I don't know, I can't do anything about it.

**Comment by AndiSlash0723** [comment]
I think it's 1.14's problem? ://

**Comment by lgou2w** [comment]
I think you can use `/timings` to statistically debug

**Comment by lgou2w** [comment]
See what causes the lag

**Comment by AndiSlash0723** [comment]
Yea.. Sure. I will try it. Thank you XD

**Comment by lgou2w** [comment]
Fixed in `7.5.1` and in [`491`](http://www.soulbound.me/job/EnchantmentsEnhance_stable/491/) build.

**Comment by AndiSlash0723** [comment]
Thank you for fixing it, I should test it on the same version of Paper I was using yesterday? Or I should wait for the full version of 1.14 Paper ://

**Comment by lgou2w** [comment]
The latest build can also

**Comment by AndiSlash0723** [comment]
Btw do you still run Minecraft server? :3

**Comment by lgou2w** [comment]
My own server?

**Comment by AndiSlash0723** [comment]
Not sure, I saw it on your Steam profile XD

**Comment by lgou2w** [comment]
Oh, it closed. I have to learn kotlin and some front-end frameworks. XDD

**Comment by AndiSlash0723** [comment]
Make plugins for yourself? XD

**Comment by lgou2w** [comment]
Maybe. But here is the issue tracking, I suggest talking about it elsewhere. :3

**Comment by AndiSlash0723** [comment]
Yea sure :3
