### ISSUE TITLE
Item disappear when using /enhance item setname on Paper 1.14

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#133]
Today I started a Paper server (Paper-1.14-b17.jar)

The plugin loaded normally but things happened when I use /enhance item setname

The item disappeared after executing the command. No errors were in the server side console.

(Holding the item -> /enhance item setname XX -> disappeared)

Please help ;w;

(EDIT : I'm was using build #491 and now #496. Also tested on Spigot 1.14, also got the same problem)

**Comment by lgou2w** [comment]
I will try to solve this issue tomorrow. 😴

**Comment by AndiSlash0723** [comment]
;w;

**Comment by 25** [comment]
Build [499](http://www.soulbound.me/job/EnchantmentsEnhance_Stable/499/)

Thank you for reporting.

**Comment by AndiSlash0723** [comment]
Thank you for fixing it :D
I will test it
