### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#134]
Ergenta:`Is this module? I love the enchants but not all the extra stuff. I'm looking for a plugin with enchants like your that can be obtained through an enchant table without all the bloat`

TODO: separate all parts of mechanism into independent modules.

**Comment by lgou2w** [comment]
Is each enchantment a separate jar module?

**Comment by 25** [comment]
Nope, I purpose that all the enhancements are contained in a separate jar.

And then the mechanism should in another jar.

**Comment by lgou2w** [comment]
okay, no problem
