### ISSUE TITLE
disabled?

### ISSUE THREAD

**Issue by sofialove0021** [25/EnchantmentsEnhance#149]
### What behaviour is observed:
disabled

### Steps to reproduce:
How did you cause the issue?

### Plugin list:
yes "red

### Environment description
1.8

### Enchantments Enhance build number:
7.6.0

### Error Log:
[erro.txt](https://github.com/25/EnchantmentsEnhance/files/3532670/erro.txt)

**Comment by 25** [comment]
`Unexpected IOException. Do Not Rename the Jar File!`

Please do not rename the jar file. And make sure your path does not contain any Unicode.

**Comment by sofialove0021** [comment]
its not renamed plugin!

**Comment by sofialove0021** [comment]
![image](https://user-images.githubusercontent.com/33380954/63636601-16107d80-c67a-11e9-821e-9adfac7ceaa0.png)

**Comment by sofialove0021** [comment]
bad support ty!!!
