### ISSUE TITLE
两个BUG，无法禁止特定的附魔与使用重载指令后，无法打开黑石背包

### ISSUE THREAD

**Issue by 1425115471** [25/EnchantmentsEnhance#160]
一：测试的第一个配置文件
disabledEnchantments:
  - Endless
  - 无尽
#禁用了这无尽这个附魔，还是会附魔出来，就是点击（强化）后，还是会附魔出（无尽）附魔，试过了（无尽）试过了（Endless）也试过了两个都写上，还是会附魔出来

二：测试的第二个配置文件
disabledEnchantments:
  - Random
  - Launch
  - Siphon
  - Thief
  - Touch
  - Crushing
  - Lifesteal
  - Plunder
  - Shield
  - Explosive
  - Blessed
  - Crits
#这些全部禁用了，还是会都附魔出来

#可能禁止附魔功能已经失效或出现了问题，我把之前配置文件都删了，进行测试还是无法禁止附魔
#插件实在太好用了，可惜这个功能要是不能修复，会出现很多破坏平衡的属性，所以希望作者可以尽快修复，感谢作者，作者如果修复成功，我愿意购买付费插件，再一次感谢作者

#插件版本：7.8.0
#服务器核心 ：spigot1.13.2

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/commit/bcc764726a2dbfe993965754fb7003ed171e22f43

已修复，请下载最新版
感谢提交bug！
