### ISSUE TITLE
UnsupportedOperationException in LDK

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#167]
ERROR Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.2
15.11 07:33:26 [Server] INFO java.lang.UnsupportedOperationException: Illegal item type 'AIR' that does not supported.
15.11 07:33:26 [Server] INFO at com.lgou2w.ldk.bukkit.item.ItemFactory.readTag(ItemFactory.kt:198) ~[?:?]
15.11 07:33:26 [Server] INFO at com.lgou2w.ldk.bukkit.item.ItemFactory.readTagSafe(ItemFactory.kt:178) ~[?:?]
15.11 07:33:26 [Server] INFO at org.pixeltime.enchantmentsenhance.manager.ItemManager.getItemEnchantLevel(ItemManager.java:86) ~[?:?]
15.11 07:33:26 [Server] INFO at org.pixeltime.enchantmentsenhance.listener.AnvilRestrict.onInventoryClick(AnvilListener.kt:18) ~[?:?]
15.11 07:33:26 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor824.execute(Unknown Source) ~[?:?]
15.11 07:33:26 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-226] 15.11 07:33:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-226]
15.11 07:33:26 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/commit/b2e7000a2b61ad9c615ea51d225154daae9adda5

**Comment by lgou2w** [comment]
Illegal item type 'AIR' that does not supported.

**Comment by lgou2w** [comment]
Just like the error message, because the item type is air. Description of the LDK `readTag` documentation **@throws [UnsupportedOperationException] If the item material is illegal. e.g.: `WALL_BANNER`.**

**Comment by lgou2w** [comment]
For **WALL_BANNER**, this material is a **TileEntity** block attached to the banner on the block. It is not a real item material! There are more, such as **AIR**, **REDSTONE_COMPARATOR_ON** etc..

**Comment by lgou2w** [comment]
So your method should judge:
```java
public static int getItemEnchantLevel(ItemStack item) {
  if (item == null || item.getType() == Material.AIR) // <-- Here
    return 0;
  try {
    NBTTagCompound tag = ItemFactory.readTagSafe(item);
    Integer level = tag.getIntOrNull("ELevel");
    return level != null ? level : 0;
  } catch (UnsupportedOperationException ex) {
    // Because illegal item material
    return 0;
  }
}
```

**Comment by 25** [comment]
Thank you for the design explanation. I was a bit confused about why it would throw an error. Turns out air is not an item material as you explained.
