### ISSUE TITLE
Item glitch

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#168]
iRedFox: 
`
I'm having a bug where if you hold something in your hand and shift right click enchantment table to open the gui it will be gone.
`

**Comment by 25** [comment]
The bug is very specific:
1. The player must be holding an item.
2. Opens the gui and the player is able to shift right click the item.
3. Item will be placed in the GUI and will disappear once the GUI is closed.

This bug will not be reproduced if the player is not holding an item.

**Comment by lgou2w** [comment]
When the handheld item is not a **block**, call **two** player interact events

**Comment by lgou2w** [comment]
I did not conduct all-depth testing. if needed, please checkout `master-#168` .

**Comment by 25** [comment]
> When the handheld item is not a **block**, call **two** player interact events

Are you describing the issues or it should've called two events?

**Comment by lgou2w** [comment]
Yes, right click will called two events. This is client side problem.

**Comment by lgou2w** [comment]
I know, Because since **Minecraft 1.9** has **left** and **right** hand holding feature. When the item held is not a block, right click will trigger twice, one is the **main (right) hand** and the other is the **off (left) hand**.

**Comment by lgou2w** [comment]
Yes, **PlayerInteractEvent** in **Bukkit 1.9** added a **`hand`** property.
