### ISSUE TITLE
Smelt gives ink sac when lapis is mined.

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#22]
### What behaviour is observed:
What was the error?
Smelt gives ink sac when lapis is mined.
### Steps to reproduce:
How did you cause the issue?
Gives a pickaxe smelt enchantment.

**Comment by madolebr** [comment]
now smelter doesnt work at all

**Comment by 25** [comment]
Tested in 1.13, and it is working.

**Comment by 25** [comment]
Tested in 1.12.2, and it is working.
