### ISSUE TITLE
cant enhance pickaxe after new update

### ISSUE THREAD

**Issue by madolebr** [25/EnchantmentsEnhance#28]
### What behaviour is observed:
just cant enhance picks. the animation plays, but no results. no stones are used either

### Steps to reproduce:
normal enhancement methods

### Plugin list:
This can be found by running `/pl`

### Environment description
spigot 1.13

### Enchantments Enhance build number:
6.1.0

### Error Log:
https://pastebin.com/nBEYDH8v

**Comment by 25** [comment]
You used a 1.12 version. Which is only compatible with 1.8 - 1.12.
If you want to use it in a 1.13 environment, you should head to my page (not directly from spigot) and download the 1.13 version.
