### ISSUE TITLE
still buggy after update

### ISSUE THREAD

**Issue by madolebr** [25/EnchantmentsEnhance#29]
Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
What behaviour is observed:
just cant enhance picks. the animation plays, but no results. no stones are used either. it says that this item can not be enhanced. touch does not work right on spawners. it mines them, but server doesnt recognise them as normal spawners so defaults back to pig. smelter enhancement is not working as well

Steps to reproduce:
normal enhancement methods

Plugin list:
This can be found by running /pl

Environment description
spigot 1.13

Enchantments Enhance build number:
6.1.0

only difference after using the 1.13 build is now the error doesnt show

**Comment by 25** [comment]
Thank you for reporting. Once the pipeline is cleared and all the testings are complete, you could download the latest version from my continuous delivery server.
