### ISSUE TITLE
smelter not working

### ISSUE THREAD

**Issue by madolebr** [25/EnchantmentsEnhance#34]
### What behaviour is observed:
no error. just not working. would any other enhancements interfere with it smelting the ores?

### Steps to reproduce:
How did you cause the issue?

### Plugin list:
This can be found by running `/pl`

### Environment description
1.13

### Enchantments Enhance build number:
6.2.0

### Error Log:
Link of the error log or stacktrace (if any, full log preferred)

**Comment by 25** [comment]
I tested it in my environment. Smelt works well.
My suggestion is that you check for Smelt in the lang.yml and config.yml to see if there are any errors.
You could also check for plugins list to see if it is caused by other plugin's interference.
