### ISSUE TITLE
lumberjack crashed server

### ISSUE THREAD

**Issue by madolebr** [25/EnchantmentsEnhance#35]
### What behaviour is observed:
pastebin file attacked below

### Steps to reproduce:
had a player going around chopping down as many forests as possible

### Plugin list:
This can be found by running `/pl`

### Environment description
1.13

### Enchantments Enhance build number:
6.2.0

### Error Log:
https://pastebin.com/LMGgtA5Y

**Comment by 25** [comment]
While I am fixing it, you could use the disabled list to disable this feature for now.

**Comment by madolebr** [comment]
i gotcha. will do for the time being. just wanted to make sure it was brought up
