### ISSUE TITLE
爆炸保护附魔存在严重bug

### ISSUE THREAD

**Issue by yeguanglingyue** [25/EnchantmentsEnhance#36]
### What behaviour is observed:
身穿带有爆炸保护或手持带有爆炸保护(PROTECTION_EXPLOSIONS	)效果的物品/装备时，破坏方块会产生爆炸(EXPLOSIVE)的附魔效果。

### Steps to reproduce:
---
### Plugin list:
---
### Environment description
服务器版本为spigot-1.13版本

### Enchantments Enhance build number:
6.1.0

### Error Log:
无报错日志

**Comment by 25** [comment]
无法重现此bug。
爆炸保护是原版附魔吗?按照插件逻辑是不会检测原版附魔的名字的。

能验证一下不是其他装备带有Explosive附魔吗？如：当你的稿子附有Explosive附魔的时候，你挖方块会爆炸。当你的稿子没有Explosive附魔，你的装备/饰品有Explosive附魔时，你挖方块也是会爆炸的。因为插件故意设定为不会基于物品种类而受限附魔。

**Comment by yeguanglingyue** [comment]
刚刚将插件更新至6.2.0，这个bug已经不存在了。

-不穿任何装备，手持爆炸保护的泥土破坏方块，正常
-穿戴仅有爆炸保护的装备破坏方块，正常
-使用带有爆炸保护的工具破坏方块，正常
-在6.1.0中未测试过穿戴/使用仅有爆炸附魔的物品时，破坏方块是否产生爆炸效果。

在此前的6.1.0版本中以上三种情况都会触发爆炸效果，现在两个附魔都没有任何问题了。
