### ISSUE TITLE
铲/锄/镐 无法使用强化附魔功能

### ISSUE THREAD

**Issue by yeguanglingyue** [25/EnchantmentsEnhance#37]
### What behaviour is observed:
铲/锄/镐头无法使用强化附魔功能，当选择工具强化模式、并将工具放入界面后，在信息栏中不显示成功几率而出现红色信息：不可以强化！无论左键强化或者右键直接跳过过程都没有任何响应。

- 期间尝试过将 铲/锄/镐 的物品名称加入到config文件中 AXE 分类下，但在工具模式下斧子仍可以正常强化附魔， 铲/锄/镐 依旧没有任何相应。

### Steps to reproduce:
How did you cause the issue?
---
### Plugin list:
---

### Environment description
spigot-1.13

### Enchantments Enhance build number:
6.1.0

### Error Log:
无报错日志

**Comment by 25** [comment]
请更新到最新版本，此问题在#29 已修复。

https://github.com/25/EnchantmentsEnhance/issues/29
