### ISSUE TITLE
爆炸保护……I come back again

### ISSUE THREAD

**Issue by yeguanglingyue** [25/EnchantmentsEnhance#38]
### What behaviour is observed:
还是那个问题……爆炸保护触发爆炸附魔特效……
昨天测试没有问题后，我就把config离ban掉爆炸保护取消掉了，今天重启服务器后发现bug仍然存在。
这次我进行了比较系统的测试：

### Steps to reproduce:

-手持仅具有爆炸保护附魔PROTECTION_EXPLOSIONS的泥土，破坏方块，触发爆炸特效
-手持仅具有爆炸附魔EXPLOSIVE的圆石，破坏方块，触发爆炸特效
-手持仅具有爆炸附魔EXPLOSIVE的胸甲，破坏方块，触发爆炸特效
-身穿仅具有爆炸附魔EXPLOSIVE的胸甲，空手破坏方块，触发爆炸特效
-身穿仅具有爆炸保护附魔PROTECTION_EXPLOSIONS的胸甲，空手破坏方块，**未触发**爆炸特效
-身穿仅具有爆炸保护附魔PROTECTION_EXPLOSIONS的胸甲，手持仅具有爆炸附魔EXPLOSIVE的圆石，破
        坏方块，触发爆炸特效
-身穿具有爆炸保护1和爆炸1的胸甲，空手破坏方块，触发爆炸特效
-身穿具有爆炸保护1和爆炸1的胸甲，手持仅具有爆炸附魔EXPLOSIVE的圆石，空手破坏方块，触发爆炸特效

综上，当且仅当同时满足手中物品无爆炸或爆炸保护附魔，身上装备没有爆炸附魔这几个条件时，空手破坏方块不会产生爆炸效果。手持爆炸保护附魔物品会触发爆炸特效。

由于没有合适的图床所以暂时未上传图片。

### Plugin list:
服务器基础插件，ess，chestcommands，quickshop，papi、vault，多世界、创世神、全息文字、斩首、领地、地皮。无其他自定义物品、附魔插件，无RPG插件。

### Environment description
spigot-1.13

### Enchantments Enhance build number:
6.2.0

### Error Log:
没有报错日志

**Comment by 25** [comment]
你可以选择使用GitHub作为图床。

```
version
[20:14:36 INFO]: This server is running CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[20:14:36 INFO]: Checking version, please wait...
[20:14:37 INFO]: You are 25 version(s) behind
enhance version
[20:14:42 INFO]: [强化插件] 您正在使用的插件版本是v6.2.0
```
我没有办法重现此bug. 上面是我的版本信息，下面是我的测试记录。
![git](https://user-images.githubusercontent.com/31719556/44962354-e6a6b500-aeec-11e8-8a7e-a4709c61e594.gif)

**Comment by yeguanglingyue** [comment]
好的，考虑到存在某些插件导致的这个问题的可能，我今天会排查下插件。发现问题所在我会继续反馈。

辛苦你了。

**Comment by 25** [comment]
爆炸保护含有爆炸可能触发爆炸附魔(?)，所以我刚才移除了模糊对比。

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/pull/40

**Comment by yeguanglingyue** [comment]
经过一上午的测试终于找到了冲突的插件：EnchantFix

这是一个国人原创的插件，好像没有上传到spigot官网，mcbbs链接为
[http://www.mcbbs.net/thread-812679-1-1.html](url)

由于本人源码渣，只能通过测试结果推测bug原因：
穿戴移除EnchantFix插件前 附魔爆炸保护的装备 会触发爆炸特效
穿戴移除EnchantFix插件后 附魔爆炸保护的装备 不会触发爆炸特效

想来应该是EnchantFix插件在处理附魔ID的时候出现了模糊或者混淆，我会将这个bug同时上报给EnchantFix插件的作者。

**Comment by 25** [comment]
已采用精确对比，下个版本兼容这个插件。
