### ISSUE TITLE
What exactly does the plugin do?

### ISSUE THREAD

**Issue by JesterOwl** [25/EnchantmentsEnhance#4]
**Description**
First off- I'd like to say I love the idea of the plugin as well as the features, and I've scouted across the spigot page, as well as the GitHub.

Unfortunately, I wasn't able to figure out how the plugin works, and I do have a few questions, and I'm sorry if this was the wrong place to post. I didn't want to post it as a review on spigot, and please tell me if there are better ways to contact the plugin author/s    (I'm really new to GitHub as well)

**Short Bio**
Working on an RPG Minecraft server so I'm in love with the idea of this plugin. I found it and installed it and proceeded to try and figure it out. I found the commands to give myself the "Enhance Stones" and upgraded a sword to Level 15. I understand how enhancing works, with failstacking, etc. because it's well described on the spigot page, even though I've never played Black Dessert Online. But here is where the problem started: the only change I noticed on the Stone Sword was the lore was changed. 

**Questions:**

**1. What does each weapon level exactly do?** For example, what is the difference between a Diamond Sword, and one that was enhanced once or twice? I saw in the config that there are options for each level, as well as the chance to get to the next level, but the only change I saw was that it seemed to add one or two enchantments added by the plugin. One example in the config is at level 3, it says "enhancements" "Damge_ALL:3" "Hex: 1." Are these the only changes done everytime you enhance up a weapon?

**2. What are accessories?** I saw no mention of this anywhere, except a short excerpt in the Config where it talks about accessory slots, I understand what the slots are.. but what do I put in them?

**3. How do I access the enchantments added to the plugin?** So I noticed there is an extensive list of enchantments on the GitHub wiki, and I was wondering exactly how to access them. Is it only available through enhancing player gear? I ask because almost all of them are not included in the default config so I was wondering if there is a different way to acquire them.

Thank you for reading my questions, I truly appreciate it because I'm really interested in the plugin and would love to use it on my future server, but then I couldn't figure it out. Again, sorry if this isn't the correct place to post, If you could direct me to the correct place, I'd really appreciate it. 
Thanks again, Jester~

**Comment by JesterOwl** [comment]
Oh and sorry. I googled and searched for a good half an hour and couldn't figure out how GitHub labels work. I tried so hard to label it as a question but I couldn't figure it out, so sorry about that as well.

**Comment by 25** [comment]
Documentation is completed. Please go to wiki to view the information. If you have any more questions, you could open another issue.
