### ISSUE TITLE
关于1.13版本砍树获取黑石的小问题

### ISSUE THREAD

**Issue by yeguanglingyue** [25/EnchantmentsEnhance#42]
### What behaviour is observed:
1.13版本，默认配置下砍树无法获取黑石

### Steps to reproduce:
默认配置砍树无论如何都不会获取黑石

这个问题很容易解决，这是由于1.13版本物品ID有大变动导致的。默认配置中是这样的：
```
 chopping:
  - LOG
  fishing:

```
只要改成
```
chopping:
  - ACACIA_LOG
  - BIRCH_LOG
  - DARK_OAK_LOG
  - JUNGLE_LOG
  - OAK_LOG
  - SPRUCE_LOG
```
就可以正常获得黑石了。

### Plugin list:
无关

### Environment description
spigot-1.13

### Enchantments Enhance build number:
6.2.0

### Error Log:
无

**Comment by 25** [comment]
发现了一个严重的问题。
感谢反馈，已经修复生活技能掉落问题。
