### ISSUE TITLE
Placeholders Not Support Plugin FeatherBoard

### ISSUE THREAD

**Issue by nuangtr** [25/EnchantmentsEnhance#44]
### What behaviour is observed:
Placeholders Not Support Plugin FeatherBoard

### Environment description
1.12.2 

### Plugin list:
This can be found by running `/pl`
Plugins (53): PlaceholderAPI, FarmProtect, MultiWorld, NoQDrops, ViaVersion, EasyHat, ViaBackwards, WorldEdit, AgarthaLib, ClearLag, ArmorStandEditor, ProtocolLib, LibsDisguises, MVdWPlaceholderAPI, Bin, NoParticles, PermissionsEx, FeatherBoard, MovingThings, Vault, PlayerShopGUIPlus, BlockParticles, BlockRegen, JustClan, HolographicDisplays, WorldGuard, MyItems, ChatItem, MythicMobs, EpicWorldGenerator, ARDamageHolograms, ShopGUIPlus, GUIPlus, Essentials, EnchantmentsEnhance, ChatControl, ChangeSkin, HeadDatabase, AdvancedAbilities, SafeTrade, KarenProtect, Citizens, Sentinel, Shopkeepers, ProQuests, RPGItems, RPGHorses, NoFlyZone, EssentialsProtect, EssentialsAntiBuild, ServerSigns, CommandNPC, CrateReloaded

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/wiki/Placeholders
