### ISSUE TITLE
Not able to fly even if Opped

### ISSUE THREAD

**Issue by Krauzzer** [25/EnchantmentsEnhance#5]
### What behaviour is observed:
It had been a while that I wasn't being able to fly on my server, nor other players. After trying to move out many plugins one by one I found out that EE was the one that was doing it. There are no errors in console.

### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
 Double tapping space doesn't make you fly, nor trying other plugins that make you fly will work.

### Plugin list:
PluginConstructorAPI, CaulCrafting, GeneralLib, BetonQuest, Trees, Recount, DropEdit, EpicWorldGenerator, NewGods, ItemRestrict, dynmap, LuckPerms, ClearLag, ChatControl, WorldBorder, Multiverse-Core, ProtocolLib, AutoSaveWorld, NoCheatPlus, LuckPerms-GUI, FastAsyncWorldEdit, LightChatBubbles, SignEditor, EffectLib, CS-CoreLib, mcMMO, BlockParticles, RealMail, TownPortal, FastAsyncVoxelSniper, PlaceholderAPI, HolographicDisplays, ChatItem, TabList, VoxelSniper, WorldEdit, WorldChangeScreenRemover, ChangeSkin, mcMMOAction, WorldGuard, Slimefun, SlimefunCustomizer, SlimefunLuckyBlocks, ExoticGarden, WGCustomFlags, EasyHarvest, ElectricSpawners, MCJukebox, PrivateStorage, NPCAuctions, AuthMe, MythicMobs, RandomTeleport, CrazyEnchantments, Denizen, Essentials, PlayerMention, Jobs, ScoreboardStats, ServerlistMOTD, Vault, GriefPrevention, ChestShop, LibelulaAutoShop, MorphMining, Citizens, TradeMe, Hydra, TimeIsMoney, Signs, dtlTraders, Magic.

### Environment description
`[Latest Spigot] [1.12.2]`

### Enchantments Enhance build number:
`[Latest]` 4.1.6

### Error Log:
`There isn't any errors or stacktraces`

**Comment by JesterOwl** [comment]
I actually had the same exact issue. I can post my plugin list if it would help. Basically, I was unable to fly in creative, or with the command /fly.

**Comment by 25** [comment]
Thanks! Please check the latest build see if the issue resolves.
