### ISSUE TITLE
Enhance menu backpack gives you gui items

### ISSUE THREAD

**Issue by TheMinecraftBrick** [25/EnchantmentsEnhance#50]
### What behaviour is observed:
When opening the backpack portion from /enhance menu
you are given any item that has an enchant on it in the gui menu, (like the selected mode etc)

### Steps to reproduce:
/enhance menu
then click on the minecart (backpack area)

### Plugin list:
yes

### Environment description
Spigot Server running 1.12.0

### Enchantments Enhance build number:
v6.5.0

### Error Log:
None.

**Comment by 25** [comment]
Are you sure it isn't materialized items? You could take those items out to trade with players.
