### ISSUE TITLE
Internal error while opening Gui and typing commands

### ISSUE THREAD

**Issue by Krauzzer** [25/EnchantmentsEnhance#6]
### What behaviour is observed:
What happened?
Can't use commands or open the Menu

### What behaviour is expected:
 The opposite from above...

### Steps/models to reproduce:
Using /enhance works, but the sub-commands wont also opening the gui doesn't work as well, the custom enchantments seems to work fine tho.

### Plugin list:
PluginConstructorAPI, CaulCrafting, GeneralLib, BetonQuest, Trees, Recount, DropEdit, EpicWorldGenerator, NewGods, ItemRestrict, dynmap, LuckPerms, ClearLag, ChatControl, WorldBorder, Multiverse-Core, ProtocolLib, AutoSaveWorld, NoCheatPlus, LuckPerms-GUI, FastAsyncWorldEdit, LightChatBubbles, SignEditor, EffectLib, CS-CoreLib, mcMMO, BlockParticles, RealMail, TownPortal, FastAsyncVoxelSniper, PlaceholderAPI, HolographicDisplays, ChatItem, TabList, VoxelSniper, WorldEdit, WorldChangeScreenRemover, ChangeSkin, mcMMOAction, WorldGuard, Slimefun, SlimefunCustomizer, SlimefunLuckyBlocks, ExoticGarden, WGCustomFlags, EasyHarvest, ElectricSpawners, MCJukebox, PrivateStorage, NPCAuctions, AuthMe, MythicMobs, RandomTeleport, CrazyEnchantments, Denizen, Essentials, PlayerMention, Jobs, ScoreboardStats, ServerlistMOTD, Vault, GriefPrevention, ChestShop, LibelulaAutoShop, MorphMining, Citizens, TradeMe, Hydra, TimeIsMoney, Signs, dtlTraders, Magic.

### Environment description
`Latest Spigot` 1.12.2

### Enchantments Enhance build number:
`Latest` 4.1.7

### Error Log:
`While trying to use the enchantment table:`
[Pastebin](https://pastebin.com/mGRWag6j)

`While trying to use /version`
[Pastebin](https://pastebin.com/j9R8uBAf)

`While trying for new Ench command`
[Pastebin](https://pastebin.com/23f5Gtfc)

**Comment by 25** [comment]
All the issues are patched. Thank you for reporting.
