### ISSUE TITLE
Error shown when enhancing a +11 item with lore to +12

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#69]
Hello and I'm new to GitHub, I dont really know how to fill up this.
Also sorry for my English and I will try my best.

I have a diamond sword with lore (Kzarka, with NBTExplorer)
(https://imgur.com/a/e4vpBAa)

I was enhancing it, everything was fine in the begin until it reached +11
I found that its not able to enhance the sword and error messages keep jumping out in the server console
(https://imgur.com/a/OqsCLwT)

Then I removed the lore (https://imgur.com/a/Zzg4ceX)
After removing it, I enhanced the sword to +12 and putted the lore back
Its able to enhance now and able to reach TRI (https://imgur.com/a/3OE7UaL)

This problem / error only show when enhancing a +11 item with lore to +12

(Pics with text : https://imgur.com/a/jwmeGAI)

Thank you.

**Comment by 25** [comment]
Thank you for reporting.

New stable version is released.
