### ISSUE TITLE
Problem of enhancing tools

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#70]
First of all sorry for my English.

I'm using v6.9.4 and I found an error when enhancing tools (Pickaxe, Hoe, Shovel and Axe)

It's able to put Pickaxe and Hoe into the enhancing interface but it will show a message about cannot enhance the item while Axe shows the probability of successful enhance. But Shovel is not able to put into the enhancing interface. (https://imgur.com/a/vPKz8VP)

Axe, Pickaxe and Hoe are able to enhance to DUO but errors occur when enhancing it to TRI. (Same error message for further enhancement.)
i) Failstacks will not be added and the enhancement level will not drop when fail the enhancement, still can be enhanced to TET or even PEN.
ii) Error message in server console for each enhancement (https://imgur.com/a/J8OJ5om)

-> Not sure the problem of not able to put Shovel into the enhancing interface is a bug or design.
-> Tools cannot force enhance like weapons and armors (also not sure the problem of  is a bug or design).

Thank you.

I will put a Chinese version below :

这次是关於"工具"方面的 (锄头 十字镐 铲子 斧头)
现时没发现武器及防具方面有问题

锄头 及 十字镐 能放进强化界面 但会显示"不能强化" 而斧头则显示机率
但按下去依然能正常强化至DUO(广) (https://imgur.com/a/vPKz8VP)

但由DUO(广)强化至TRI(故)时会开始出现错误
(此错误信息 与 TRI(故)强化至TET(琉) 及 强化至TET(琉)强化至PEN(东)的错误信息为一样)
(https://imgur.com/a/J8OJ5om)
而工具在强化失败後并没有掉阶及增加层数 随便按几下就能一直升

另外 铲子不能放进强化界面内 (不清楚是内部设计还是BUG)
(不过有点好奇 工具不能与武器及防具一样强制突破 是内部的设计还是BUG?)

谢谢

**Comment by 25** [comment]
Tools now can be enhanced.

See [Changelog ](https://github.com/25/EnchantmentsEnhance/blob/master/CHANGELOG.md#700---2019-2-25)for more details.

Thank you for the detailed report!
