### ISSUE TITLE
Little problem when enhancing tools.

### ISSUE THREAD

**Issue by AndiHug** [25/EnchantmentsEnhance#72]
Thank you for the fix!! >.<

I've tested it on my server (v7.0.0 #329)
Pickaxe, Hoe and Axe can be enhanced normally when enhancing for TRI and further.
(I love the selection of enhancing Axe : Can be selected to be a weapon or tool)

But there are still some problems with it by far :

i) No probability of successful enhancement shown for Pickaxe and Hoe. (https://imgur.com/a/vPKz8VP)
(Still the same message shown which is about telling that this tool cannot be enhanced but it actually can, just that no probability of successful enhancement were shown and they can be enhanced normally with no errors)

ii) Force enhancement on tools only cost 1 black stone no matter what level it is now.
(Wrong amount of black stone required in force enhancement in different level, I suggest to let the required amount to be the same as weapons' and armors' does)

iii) Shovels are still not able to be putted into the interface (Not really sure this is a bug or a design for further)

Thank you ^^

I will put a Chinese version below :

刚刚测试了新版本 (v7.0.0 #329)

锄头 十字镐 斧头 都可以正常的强化
到了DUO(广)後强化的问题都解决了
(超爱斧头那边能选择强化成武器还是工具)

只是 依然找到一些BUG :

i) 锄头 十字镐 依然会显示"不可以强化!" 但其实是可以正常的强化 (https://imgur.com/a/vPKz8VP)
(能正常地强化至TRI(故)或更高 失败会加层数跟掉阶 但依然不能查看成功机率)

ii) 强制突破(强突)所需数量没有变化(每个等级都一样)
(不确定+15後的数值是否正确 因为我设定了+15後不能强突 但+15前强突所需的黑石数量 每个等级都一样 全都是1个黑石 没有变化 我建议让工具强突时每等级所需的黑石数量跟武器/防具每等级强突所需黑石数量一样)

iii) 铲子依旧不能放进强化界面内及进行强化 (不肯定这是BUG还是设计)

感谢 ^^

(我的帐号不知道为什麽被封了= = 等解封中...)

**Comment by 25** [comment]
Hey，请不要删除Issue，因为issue是用来记录变更的。

可能之前你删除了多个issues被GitHub标记成滥用了。

**Comment by 25** [comment]
忘记了铲子的存在，马上就会添加

**Comment by AndiHug** [comment]
我没有删除啦XD 是昨晚突然被封了
之後帐号的东西都被隐藏了
希望他们能早点解封

**Comment by 25** [comment]
xD
请测试一下最新的构建

**Comment by AndiHug** [comment]
刚刚测试了 v7.0.0 (#331)

上述的问题 :

i) 锄头 十字镐 原本会显示"不可以强化!" 现时会显示机率

ii) 工具强突时黑石所需量而有更变

iii) 铲子能放进强化界面内及进行强化

总结 : 3个问题都已解决

未来再发现有bug会继续回报

谢谢. ^^
