### ISSUE TITLE
A little suggestion on enhancing swords.

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#73]
A little suggestion on enhancing swords.

Axe can be enhanced to weapon or tool. This is a very very great function since the Axe could be the weapon of Berserker and a tool of cutting trees.

I suggest that adding sword into in to make swords can be picked to be enhanced as weapon or tools.

Thank you

I will put a Chinese version below :

关於强化剑方面的一个小建议

斧头可以选择强化为武器或生活工具
这功能可以让斧头强化为狂战士的武器或伐木用的生活工具

我建议把剑设定成跟斧头一样 可以选择强化为武器或生活工具
这样就能强化出黑色沙漠中的屠宰用刀及制革用刀
而随着强化的方向不同 有不同的效果出现

以上是我的一个小小的建议 谢谢^^

**Comment by 25** [comment]
已添加。
