### ISSUE TITLE
Cannot see the amount of blackstones that I have.

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#74]
I found a little bug.

I was enhancing an Axe as tool. I accidentally clicked the minecart (where we see the amount of blackstone that we own) and the menu was shutted by itself.

The server console has shown 2 errors.
The first one is before I rejoin the server and the second one is after rejoining the server.
(https://imgur.com/a/mgWAv9G)

Thank you ^^

I will put a Chinese version below :

刚刚在强化一把斧头作工具时发现的bug

我那时打算查看我拥有的忠告 但不小心按到查看拥有的黑石的按钮
后来界面自己关掉了 并在伺服器那边跑出错误讯息

跑出的错误讯息有2种
第一种是一开始出现的
而第二种是重新加入伺服器后出现的
(https://imgur.com/a/mgWAv9G)

以后有bug/错误会继续回报

谢谢^^ (我先去睡了

**Comment by 25** [comment]
需要完整log

**Comment by 25** [comment]
Help wanted: async lock for GUI.

Allow the plugin to disable some functionalities of the button when the enhancing animation begins. Also, allow the user to use buttons to cancel the enhancement.

**Comment by AndiSlash0723** [comment]
这问题在重启伺服器后消失了 = =
满奇怪的..

**Comment by 25** [comment]
语言文件抛出空指针，可能是修改lang文件时变动了什么?

**Comment by AndiSlash0723** [comment]
hmmm 这个我要再回去查一下lang文件
改动就没太大 全都是翻译到繁中
只有突破那边把公告改了一改 看起来比较像台服的公告XP

**Comment by 25** [comment]
如果你想的话可以共享你的config和lang文件噢

有贡献者称号的鸭

**Comment by AndiSlash0723** [comment]
哈哈可以啊 但目前还在调查中 在哪里可以上传?

不过说起config
我在想 这插件能重新命名道具
会不会可以加个功能 : 只能强化经插件命名道具 而这功能可以在config里设定开启或不开启
因为这个插件 配合不同道具 可以高度还原黑色沙漠的一部分 真的很好 例如巴雷斯系统的主武器 克价卡 奥平等等的王武 而防具也是 也能还原一些生活工具
以上是我的一个小建议XD 以后想到的会继续提交

文件方面 我调整好了就可以分享 :D

**Comment by 25** [comment]
插件有自查纠错功能，如果配置文件不存在，在重启的时候会自动读写添加。

你看看有没有重复的就应该知道了

**Comment by 25** [comment]
文件可以直接拉到GitHub的输入框

**Comment by AndiSlash0723** [comment]
好的 目前还在调整中 之后差不多的时候就会放上来XD
而文件方面 没有发现有重复的文件

不过 我还有些小建议 我会在下面解说一下
(看看用不用开一个新的issue 要的话我整理一下再开一个新的issue放建议)

i) 如上 在config内选择开不开启"只限强化经插件命名的道具"
(我有留意到经插件命名的物品会有一个叫EName的标签 而这功能就像 检查物件有没有EName这标签 有的话才给强化 没有就不给)
我的伺服器内有安装大大的插件 大多数玩家都表示好评 表示很爱这插件 也增加了不少乐趣
而对我(伺服器拥有人及管理员)来说也是好评XD而同时也能创造出一种新的玩法让玩家去体验 插件能高度还原黑色沙漠 强化系统 装备等等
假如能加入上述功能的话 能让走黑色沙漠路线的玩家带来更多欢乐

ii) 有玩家反映游戏内的附魔台一打开就是强化界面 希望能选择附魔台是否变成强化界面令两类玩家(走Minecraft原本路线的及走黑色沙漠路线的玩家)能同时生存而不影响到对方(感觉假如能在config中设定的话会比较好?)

iii) 希望能强化 盾牌 及 鱼竿
在黑色沙漠中盾牌为战士的副武器有玩家表示假如能强化盾牌则能更高度地还原黑色沙漠
而鱼竿方面则希望像黑色沙漠一样最高能强化到+10(而在+7开始强化失败就会掉强化等级)

iv) 希望能加入一个分辨"武器"及"生活工具"的标签
个人认为假如能加入一个上述的标签能减少玩家错误地强化武器或生活工具的情况发生
因为有玩家误把生活工具强化成武器 也有玩家误把武器强化成生活工具(例如斧头可以是狂战子的武器也可以是伐木工具)
若果加入标签 当玩家点击被标签道具时 自动切换装备强化模式及工具强化模式
(而加入标签功能的同时 也能让更多道具可以同时为武器及生活工具 这样相信能帮助更高度还原黑色沙漠)

我爱黑色沙漠 也爱这插件 希望能透过提供建议来让插件变得更好^_^

以上是一些小小的建议 希望能被采用
(有需要的话我会开一个新的issue)

BTW今天有玩家跟我说他打开强化界面后 宠物不小心踩到qwer上面那行数字键之后装备就被放到强化界面内 按取消也不能拿下来 把强化界面关闭后装备直接消失了(不肯定当时他有没有按着其他键但系伺服器那边没显示任何东西/错误有点诡异XD)

(先去睡觉了 明天要早起)

**Comment by 25** [comment]
每一个建议请新开一个新的issue

**Comment by AndiSlash0723** [comment]
好的 我之后再开

但有点好奇想问一下
通常一个建议 假如被采用的话
建议提及的功能大约会在多久之后推出?

**Comment by 25** [comment]
根据我的代码结构吧，有的时候设计的时候没有考虑到的功能必须重写整个插件才能实现

**Comment by 25** [comment]
ii) 第二个问题可以设置 [WIKI](https://github.com/25/EnchantmentsEnhance/wiki/%E9%99%84%E9%AD%94%E5%BC%BA%E5%8C%96%E5%AE%8C%E6%95%B4%E6%96%87%E6%A1%A3#%E6%89%93%E5%BC%80%E5%A2%9E%E5%BC%BA%E8%8F%9C%E5%8D%95)

**Comment by 25** [comment]
最後的那個錯誤修復了，是個非常嚴重的BUG
