### ISSUE TITLE
Error trying to use /enhance lore

### ISSUE THREAD

**Issue by Krauzzer** [25/EnchantmentsEnhance#8]
### What behaviour is observed:
An error has occurred.

### What behaviour is expected:
 Being able to add lore to the item. In this case specifically tradeable/untradeable

### Steps/models to reproduce:
Executing the command

### Plugin list:
`Plugins (81): PluginConstructorAPI, VoidWorld, CaulCrafting, GeneralLib, ConsoleSpamFix, BetonQuest, Trees, Recount, DropEdit, EpicWorldGenerator, NewGods, ItemRestrict, dynmap, LuckPerms, ClearLag, ChatControl, WorldBorder, Multiverse-Core, ProtocolLib, AutoSaveWorld, LuckPerms-GUI, FastAsyncWorldEdit, LightChatBubbles, SignEditor, EffectLib, ConditionalCommands, CS-CoreLib, mcMMO, BlockParticles, RealMail, TownPortal, FastAsyncVoxelSniper, PlaceholderAPI, HolographicDisplays, ChatItem, TabList, VoxelSniper, AntiJigsaw, WorldEdit, WorldChangeScreenRemover, ChangeSkin, mcMMOAction, React, WorldEditSelectionVisualizer, WorldGuard, Slimefun, SlimefunCustomizer, SlimefunLuckyBlocks, ExoticGarden, WGCustomFlags, EasyHarvest, ElectricSpawners, MCJukebox, PrivateStorage, NPCAuctions, AuthMe, MythicMobs, RandomTeleport, WorldGuardExtraFlags, CrazyEnchantments, Denizen, Essentials, PlayerMention, EnchantmentsEnhance, CompatNoCheatPlus, NoCheatPlus, Jobs, ScoreboardStats, ServerlistMOTD, Vault, GriefPrevention, ChestShop, LibelulaAutoShop, MorphMining, Citizens, TradeMe, Hydra, TimeIsMoney, Signs, dtlTraders, Magic
`

### Environment description
Latest spigot/ 1.12.2

### Enchantments Enhance build number:
v. 4.2.2

### Error Log:
`20:00:14 [INFO] Krauser issued server command: /enhance lore addhand`
```
20:00:14 [WARN] java.lang.NullPointerException
20:00:14 [WARN] 	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
20:00:14 [WARN] 	at org.pixeltime.enchantmentsenhance.util.Util.sendMessage(Util.java:93)
20:00:14 [WARN] 	at org.pixeltime.enchantmentsenhance.event.blackspirit.Lore.addLore(Lore.java:91)
20:00:14 [WARN] 	at org.pixeltime.enchantmentsenhance.command.player.LoreCommand.onCommand(LoreCommand.java:33)
20:00:14 [WARN] 	at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:137)
20:00:14 [WARN] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20:00:14 [WARN] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20:00:14 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
20:00:14 [WARN] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:00:14 [WARN] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
20:00:14 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
20:00:14 [WARN] 	at java.lang.Thread.run(Thread.java:748)
```

### Configuration:
Link of your config.yml file(if error was caused by lang exception)

**Comment by 25** [comment]
Hi, thank you for the bug report. The issue is patched and the lore is improved.
