### ISSUE TITLE
Suggestion on giving a function of enabling or disabling "Only renamed items enhancement only"

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#85]
It's kinda hard to explain in English since my English is not really good.

I will just leave a Chinese version of it :

在config内选择开不开启"只限强化经插件命名的道具"
(我有留意到经插件命名的物品会有一个叫EName的标签 而这功能就像 检查物件有没有EName这标签 有的话才给强化 没有就不给)
我的伺服器内有安装大大的插件 大多数玩家都表示好评 表示很爱这插件 也增加了不少乐趣
而对我(伺服器拥有人及管理员)来说也是好评XD而同时也能创造出一种新的玩法让玩家去体验 插件能高度还原黑色沙漠 强化系统 装备等等
假如能加入上述功能的话 能让走黑色沙漠路线的玩家带来更多欢乐

**Comment by 25** [comment]
如果开启这个功能后，玩家如何获得带有ENAME的标签？

**Comment by AndiSlash0723** [comment]
意思是 假如开启了这功能 玩家会怎样才能获得有ENAME标签的物品吗?

我认为 这功能可以让以黑色沙漠作主题的伺服器开启 而不需要的则不用开启

以我现在的伺服器为例 里面有推出克价卡 奥平等等的武器(但它们为经插件命名的钻石剑 因此有ENAME的标签)

而获得方法为击败野外boss/世界王 以他们掉落的交换卷作交换

上面提及的功能 可以避免不公平的情况出现
(例如 以合成方法获得钻石剑的玩家 能拥有辛苦把交换卷打回来的玩家的武器 什至强化数值)

(假如被采纳 建议在config内新增是否开启此功能的选项 ^_^)

**Comment by 25** [comment]
已添加
