### ISSUE TITLE
Tag of items to identify its a weapon or armor or others.

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#87]
It's kinda hard to explain in English since my English is not really good.

I will just leave a Chinese version of it :

希望能加入一个分辨"武器"及"生活工具"的标签
个人认为假如能加入一个上述的标签 能减少玩家错误地强化武器或生活工具的情况发生

因为有玩家误把生活工具强化成武器 也有玩家误把武器强化成生活工具(例如斧头可以是狂战子的武器也可以是伐木工具)

若果加入标签 当玩家点击被标签道具时 自动切换装备强化模式及工具强化模式
(而加入标签功能的同时 也能让更多道具可以同时为武器及生活工具 这样相信能帮助更高度还原黑色沙漠)

**Comment by 25** [comment]
一旦一个物品被强化成`武器`，这个道具不能被赋予更多的类型。

所以战斗斧不会被强化成伐木工具的

**Comment by AndiSlash0723** [comment]
我尽力解释一下

例如在"/enhance item" 里面新增一个功能
可以把一件物件设定为武器或其他用途 (例如 生活工具)
(感觉像加一个"武器"或"生活工具"的标签到一个物件上?)

这样能把一件物件可以同时被定位成不同用途的道具
例如 一把斧头 假如它被用家用指令 指定设为生活工具 那它之后的强化效果等等就会是工具型的斧头(例如 伐木用的斧头)
那 假若它被用家用指令 指定设为武器 那它之后的强化效果等等就会是武器型的斧头

例如有一个指令 "/enhance item set {种类}" 而种类则为武器(weapon)/防具(armor) 及生活工具(tools)

假如玩家手拿着斧头 输入 "/enhance item set weapon" 那该斧头就会标签为武器(战斗斧)
假如玩家输入的是"/enhance item set tools" 那该斧头就会标签为生活工具(工具斧)
之后根据物件的标签 自动选择强化模式为武器或生活工具
(再之后就跟现有的差不多 武器的就给予武器的强化效果 工具就给予工具的强化效果)

我尽力了XDD 感觉还是复杂

**Comment by 25** [comment]
/enhance item { upgrade {type} {level} }

你现在可以用升级指令指定物品的type

type有 gear, tool.

**Comment by AndiSlash0723** [comment]
我可以在哪里下载? 有兴趣尝试一下

**Comment by 25** [comment]
http://www.soulbound.me/job/EnchantmentsEnhance_Stable/360/

**Comment by AndiSlash0723** [comment]
刚刚测试了 不错^^ (暂时无错误)

不过想问一下 之后会有极防具改良石/极武器改良石的出现吗?
印象中lang文件好似有一个地方是关于极防具改良石/极武器改良石的
我打算在自己的伺服器中推出极防具及极武器 想先问一下极防具改良石/极武器改良石之后会更新吗? 还是我会需要自己弄道具? 0.0
