### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Krauzzer** [25/EnchantmentsEnhance#9]
### What behaviour is observed:
I see that there are some changes with the enchantments names, but there's no documentation about what they are since they're missing inside the Wiki or everywhere else, are you planning to keep those or are they just for testing?
  - Also there are some duplicates on config.yml, them being: EMERALD_ORE over life skills, and WOOD_AXE over weapons.

### What behaviour is expected:
  Some info about the new contents. It would also be more pratical to have the `enhance` section of config.yml for equipment's upgrades over a new folder/file.

  - Great progress with your plugin so far 😄👍

**Comment by 25** [comment]
All the features are implemented and the wiki is now up-to-date. Thank you for the suggestion!
