### ISSUE TITLE
Plugin confusion

### ISSUE THREAD

**Issue by ArksOminous** [25/EnchantmentsEnhance#95]
Love the idea of the plugin. still trying to figure it out. Im lost on the concept of obtaining and accesing the stones. like... lifeskills? what exactly do those consist of, and u have a chance of getting the stone at the end of the task? Is there a way to see the tasks that i am just missing? Also a couple of suggestions:

If you could, i would talk to the Dev of Zenchantments if you can, his plug in has many very unique and interesting enchantments such as scattershot and rapid fire for bows, blizzard, firestorm, vortex, apocalypse, ect..

And is there a way you could condense the text in the GUI menu? The words run off the screen and such i cant read most of whats in the menu.

**Comment by 25** [comment]
See [wiki](https://github.com/25/EnchantmentsEnhance/wiki/The-Complete-Guide-to-EnchantmentsEnhance#-life-skill) about lifeskill

**Comment by 25** [comment]
Interesting proposal. Zenchantments would be a very good plugin to integrate into this plugin because it has many unique enchantments and it is open source. I will refer this proposal to the author of Zenchantments.

@Zedly

**Comment by ArksOminous** [comment]
thank you much, it seems im just blind as always, and anything about he GUI text?

**Comment by 25** [comment]
Could you attach an image showing that the text is rendered outside of the screen?

**Comment by ArksOminous** [comment]
![image](https://user-images.githubusercontent.com/48167897/53691058-8c27cd80-3d44-11e9-8fc6-9dab0a01e866.png)
![image](https://user-images.githubusercontent.com/48167897/53691065-a2ce2480-3d44-11e9-9070-d58cd3cdb05a.png)

Those are a few. Theres a bit of every description in the backpack section that gets a bit cut off. now technically I can set my GUI scale to 3 instead of default but not everyone is gonna think of that or want to do it.
