### ISSUE TITLE
Suggestion : Player name in PEN items' description

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#97]
有个小想法
在东的装备里加上制作者的名字
像这样子 : 
![image](https://user-images.githubusercontent.com/47967939/53729074-328fe200-3eaf-11e9-9027-27229afc568d.png)

那两句 :
"该装备献给伟大的冒险家"
制作者 : (玩家名字)

(别在意东巴雷斯= =)

**Comment by 25** [comment]
已添加，请测试构建
http://www.soulbound.me/job/EnchantmentsEnhance_Stable/389/
